### ISSUE TITLE
Desenhar protótipo de alta fidelidade da Pagina Home

### ISSUE THREAD

**Issue by manusil099** [tads-extensao-I/PuroQueijo#3]
# Desenhar protótipo de alta fidelidade considerando as informações que farão parte do site real.

**Comment by nicholas-santos-ifms** [comment]
![Protótipo de Alta Fidelidade](https://github.com/tads-extensao-I/PuroQueijo/assets/112990209/5a74bfb1-e0ab-49ed-9567-6a1c433812db)
